const alkaliMetal = '#ffb4a2'
const alkalineEarth = '#a5c7d4'
const transitionMetal = '#f0c987'
const basicMetal = '#c8a7d1'
const semimetal = '#bbb9c5'
const nonmetal = '#6decb9'
const halogen = '#a0f4db '
const nobleGas = '#db92b2'
const lanthanide = '#ffd3b6'
const actinide = 'e1c6d9'

const elements = {
    H: nonmetal,
    He: nobleGas,
    Li: alkaliMetal,
    Be: alkalineEarth,
    B: semimetal,
    C: nonmetal,
    N: nonmetal,
    O: nonmetal,
    F: halogen,
    Ne: nobleGas, // 10
    Na: alkaliMetal,
    Mg: alkalineEarth,
    Al: basicMetal,
    Si: semimetal,
    P: nonmetal,
    S: nonmetal,
    Cl: halogen,
    Ar: nobleGas,
    K: alkaliMetal,
    Ca: alkalineEarth,
    Sc: transitionMetal,
    Ti: transitionMetal,
    V: transitionMetal,
    Cr: transitionMetal,
    Mn: transitionMetal,
    Fe: transitionMetal,
    Co: transitionMetal,
    Ni: transitionMetal,
    Cu: transitionMetal,
    Zn: transitionMetal,
    Ga: basicMetal,
    Ge: semimetal,
    As: semimetal,
    Se: nonmetal,
    Br: halogen,
    Kr: nobleGas, // 36
    Rb: alkaliMetal,
    Sr: alkalineEarth,
    Y: transitionMetal,
    Zr: transitionMetal,
    Nb: transitionMetal,
    Mo: transitionMetal,
    Tc: transitionMetal,
    Ru: transitionMetal,
    Rh: transitionMetal,
    Pd: transitionMetal,
    Ag: transitionMetal,
    Cd: transitionMetal,
    In: basicMetal,
    Sn: basicMetal,
    Sb: semimetal,
    Te: semimetal,
    I: halogen,
    Xe: nobleGas,
    Cs: alkaliMetal,
    Ba: alkalineEarth,
    Hf: transitionMetal,
    Ta: transitionMetal,
    W: transitionMetal,
    Re: transitionMetal,
    Os: transitionMetal,
    Ir: transitionMetal,
    Pt: transitionMetal,
    Au: transitionMetal,
    Hg: transitionMetal,
    Tl: basicMetal,
    Pb: basicMetal,
    Bo: basicMetal,
    Po: semimetal,
    At: halogen,
    Rn: nobleGas,
    Fr: alkaliMetal,
    Ra: alkalineEarth,
    Rf: transitionMetal,
    Db: transitionMetal,
    Sg: transitionMetal,
    Bh: transitionMetal,
    Hs: transitionMetal,
    Mt: transitionMetal,
    Ds: transitionMetal,
    Rg: transitionMetal,
    Cn: transitionMetal,
    Nh: basicMetal,
    Fl: basicMetal,
    Mc: basicMetal,
    Lv: basicMetal,
    Ts: halogen,
    Og: nobleGas,
    La: lanthanide,
    Ce: lanthanide,
    Pr: lanthanide,
    Nd: lanthanide,
    Pm: lanthanide,
    Sm: lanthanide,
    Eu: lanthanide,
    Gd: lanthanide,
    Tb: lanthanide,
    Dy: lanthanide,
    Ho: lanthanide,
    Er: lanthanide,
    Tm: lanthanide,
    Yb: lanthanide,
    Lu: lanthanide,
    Ac: actinide,
    Th: actinide,
    Pa: actinide,
    U: actinide,
    Np: actinide,
    Pu: actinide,
    Am: actinide,
    Cm: actinide,
    Bk: actinide,
    Cf: actinide,
    Es: actinide,
    Fm: actinide,
    Md: actinide,
    No: actinide,
    Lr: actinide,
}

export default elements
